/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Role = IDL.Variant({
  'ADMIN' : IDL.Null,
  'OWNER' : IDL.Null,
  'EMPLOYEE' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'checkIn' : IDL.Int,
  'userId' : IDL.Principal,
  'checkOut' : IDL.Opt(IDL.Int),
  'gpsLat' : IDL.Float64,
  'gpsLng' : IDL.Float64,
});
export const Department = IDL.Variant({
  'BAR' : IDL.Null,
  'BARBERSHOP' : IDL.Null,
  'GAS_STATION' : IDL.Null,
});
export const EmployeeProfileInput = IDL.Record({
  'salary' : IDL.Float64,
  'userId' : IDL.Principal,
  'department' : Department,
  'position' : IDL.Text,
});
export const EmployeeProfile = IDL.Record({
  'id' : IDL.Nat,
  'salary' : IDL.Float64,
  'performanceScore' : IDL.Float64,
  'userId' : IDL.Principal,
  'department' : Department,
  'position' : IDL.Text,
});
export const LocationInput = IDL.Record({
  'name' : IDL.Text,
  'radius' : IDL.Float64,
  'gpsLat' : IDL.Float64,
  'gpsLng' : IDL.Float64,
});
export const Location = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'radius' : IDL.Float64,
  'gpsLat' : IDL.Float64,
  'gpsLng' : IDL.Float64,
});
export const MeetingInput = IDL.Record({
  'title' : IDL.Text,
  'participants' : IDL.Vec(IDL.Principal),
  'date' : IDL.Int,
  'description' : IDL.Text,
});
export const Meeting = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'participants' : IDL.Vec(IDL.Principal),
  'date' : IDL.Int,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfileInput = IDL.Record({
  'name' : IDL.Text,
  'role' : Role,
  'photoUrl' : ExternalBlob,
  'email' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'photoUrl' : ExternalBlob,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
});
export const ReportPeriod = IDL.Variant({
  'MONTHLY' : IDL.Null,
  'DAILY' : IDL.Null,
  'YEARLY' : IDL.Null,
  'WEEKLY' : IDL.Null,
});
export const Report = IDL.Record({
  'to' : Timestamp,
  'expense' : IDL.Float64,
  'period' : ReportPeriod,
  'from' : Timestamp,
  'income' : IDL.Float64,
  'profit' : IDL.Float64,
  'department' : IDL.Opt(Department),
});
export const TransactionType = IDL.Variant({
  'INCOME' : IDL.Null,
  'EXPENSE' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : TransactionType,
  'date' : Timestamp,
  'createdBy' : IDL.Principal,
  'notes' : IDL.Text,
  'category' : IDL.Text,
  'department' : Department,
  'amount' : IDL.Float64,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'reviewedBy' : IDL.Principal,
  'score' : IDL.Float64,
  'employeeId' : IDL.Nat,
  'comments' : IDL.Text,
});
export const TransactionInput = IDL.Record({
  'transactionType' : TransactionType,
  'notes' : IDL.Text,
  'category' : IDL.Text,
  'department' : Department,
  'amount' : IDL.Float64,
});
export const NotificationInput = IDL.Record({
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'message' : IDL.Text,
});
export const ReviewInput = IDL.Record({
  'score' : IDL.Float64,
  'employeeId' : IDL.Nat,
  'comments' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, Role], [IDL.Bool], []),
  'checkIn' : IDL.Func([IDL.Float64, IDL.Float64], [AttendanceRecord], []),
  'checkOut' : IDL.Func([], [IDL.Opt(AttendanceRecord)], []),
  'createEmployeeProfile' : IDL.Func(
      [EmployeeProfileInput],
      [EmployeeProfile],
      [],
    ),
  'createLocation' : IDL.Func([LocationInput], [Location], []),
  'createMeeting' : IDL.Func([MeetingInput], [Meeting], []),
  'createUser' : IDL.Func([IDL.Principal, UserProfileInput], [UserProfile], []),
  'deactivateUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'deleteEmployeeProfile' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteLocation' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMeeting' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteNotification' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'generateReport' : IDL.Func(
      [ReportPeriod, IDL.Opt(Department), Timestamp, Timestamp],
      [Report],
      ['query'],
    ),
  'getAttendanceRecord' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployeeProfile' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(EmployeeProfile)],
      ['query'],
    ),
  'getLocation' : IDL.Func([IDL.Nat], [IDL.Opt(Location)], ['query']),
  'getMeeting' : IDL.Func([IDL.Nat], [IDL.Opt(Meeting)], ['query']),
  'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'listAttendanceByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'listEmployees' : IDL.Func([], [IDL.Vec(EmployeeProfile)], ['query']),
  'listEmployeesByDepartment' : IDL.Func(
      [Department],
      [IDL.Vec(EmployeeProfile)],
      ['query'],
    ),
  'listLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
  'listMeetings' : IDL.Func([], [IDL.Vec(Meeting)], ['query']),
  'listMyAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'listMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'listReviewsForEmployee' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'listTransactions' : IDL.Func(
      [
        IDL.Opt(TransactionType),
        IDL.Opt(Department),
        IDL.Opt(Timestamp),
        IDL.Opt(Timestamp),
      ],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'listTransactionsByDepartment' : IDL.Func(
      [Department],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [IDL.Nat], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'recordTransaction' : IDL.Func([TransactionInput], [Transaction], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
  'sendNotification' : IDL.Func([NotificationInput], [Notification], []),
  'submitReview' : IDL.Func([ReviewInput], [Review], []),
  'updateEmployeeProfile' : IDL.Func(
      [IDL.Nat, EmployeeProfileInput],
      [IDL.Opt(EmployeeProfile)],
      [],
    ),
  'updateLocation' : IDL.Func(
      [IDL.Nat, LocationInput],
      [IDL.Opt(Location)],
      [],
    ),
  'updateMeeting' : IDL.Func([IDL.Nat, MeetingInput], [IDL.Opt(Meeting)], []),
  'updatePerformanceScore' : IDL.Func([IDL.Nat, IDL.Float64], [IDL.Bool], []),
  'updateUser' : IDL.Func(
      [IDL.Principal, UserProfileInput],
      [IDL.Opt(UserProfile)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({
    'ADMIN' : IDL.Null,
    'OWNER' : IDL.Null,
    'EMPLOYEE' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'checkIn' : IDL.Int,
    'userId' : IDL.Principal,
    'checkOut' : IDL.Opt(IDL.Int),
    'gpsLat' : IDL.Float64,
    'gpsLng' : IDL.Float64,
  });
  const Department = IDL.Variant({
    'BAR' : IDL.Null,
    'BARBERSHOP' : IDL.Null,
    'GAS_STATION' : IDL.Null,
  });
  const EmployeeProfileInput = IDL.Record({
    'salary' : IDL.Float64,
    'userId' : IDL.Principal,
    'department' : Department,
    'position' : IDL.Text,
  });
  const EmployeeProfile = IDL.Record({
    'id' : IDL.Nat,
    'salary' : IDL.Float64,
    'performanceScore' : IDL.Float64,
    'userId' : IDL.Principal,
    'department' : Department,
    'position' : IDL.Text,
  });
  const LocationInput = IDL.Record({
    'name' : IDL.Text,
    'radius' : IDL.Float64,
    'gpsLat' : IDL.Float64,
    'gpsLng' : IDL.Float64,
  });
  const Location = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'radius' : IDL.Float64,
    'gpsLat' : IDL.Float64,
    'gpsLng' : IDL.Float64,
  });
  const MeetingInput = IDL.Record({
    'title' : IDL.Text,
    'participants' : IDL.Vec(IDL.Principal),
    'date' : IDL.Int,
    'description' : IDL.Text,
  });
  const Meeting = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'participants' : IDL.Vec(IDL.Principal),
    'date' : IDL.Int,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfileInput = IDL.Record({
    'name' : IDL.Text,
    'role' : Role,
    'photoUrl' : ExternalBlob,
    'email' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'photoUrl' : ExternalBlob,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
  });
  const ReportPeriod = IDL.Variant({
    'MONTHLY' : IDL.Null,
    'DAILY' : IDL.Null,
    'YEARLY' : IDL.Null,
    'WEEKLY' : IDL.Null,
  });
  const Report = IDL.Record({
    'to' : Timestamp,
    'expense' : IDL.Float64,
    'period' : ReportPeriod,
    'from' : Timestamp,
    'income' : IDL.Float64,
    'profit' : IDL.Float64,
    'department' : IDL.Opt(Department),
  });
  const TransactionType = IDL.Variant({
    'INCOME' : IDL.Null,
    'EXPENSE' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : TransactionType,
    'date' : Timestamp,
    'createdBy' : IDL.Principal,
    'notes' : IDL.Text,
    'category' : IDL.Text,
    'department' : Department,
    'amount' : IDL.Float64,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'reviewedBy' : IDL.Principal,
    'score' : IDL.Float64,
    'employeeId' : IDL.Nat,
    'comments' : IDL.Text,
  });
  const TransactionInput = IDL.Record({
    'transactionType' : TransactionType,
    'notes' : IDL.Text,
    'category' : IDL.Text,
    'department' : Department,
    'amount' : IDL.Float64,
  });
  const NotificationInput = IDL.Record({
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'message' : IDL.Text,
  });
  const ReviewInput = IDL.Record({
    'score' : IDL.Float64,
    'employeeId' : IDL.Nat,
    'comments' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, Role], [IDL.Bool], []),
    'checkIn' : IDL.Func([IDL.Float64, IDL.Float64], [AttendanceRecord], []),
    'checkOut' : IDL.Func([], [IDL.Opt(AttendanceRecord)], []),
    'createEmployeeProfile' : IDL.Func(
        [EmployeeProfileInput],
        [EmployeeProfile],
        [],
      ),
    'createLocation' : IDL.Func([LocationInput], [Location], []),
    'createMeeting' : IDL.Func([MeetingInput], [Meeting], []),
    'createUser' : IDL.Func(
        [IDL.Principal, UserProfileInput],
        [UserProfile],
        [],
      ),
    'deactivateUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'deleteEmployeeProfile' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteLocation' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMeeting' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteNotification' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'generateReport' : IDL.Func(
        [ReportPeriod, IDL.Opt(Department), Timestamp, Timestamp],
        [Report],
        ['query'],
      ),
    'getAttendanceRecord' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployeeProfile' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(EmployeeProfile)],
        ['query'],
      ),
    'getLocation' : IDL.Func([IDL.Nat], [IDL.Opt(Location)], ['query']),
    'getMeeting' : IDL.Func([IDL.Nat], [IDL.Opt(Meeting)], ['query']),
    'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'listAttendanceByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'listEmployees' : IDL.Func([], [IDL.Vec(EmployeeProfile)], ['query']),
    'listEmployeesByDepartment' : IDL.Func(
        [Department],
        [IDL.Vec(EmployeeProfile)],
        ['query'],
      ),
    'listLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
    'listMeetings' : IDL.Func([], [IDL.Vec(Meeting)], ['query']),
    'listMyAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'listMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'listReviewsForEmployee' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'listTransactions' : IDL.Func(
        [
          IDL.Opt(TransactionType),
          IDL.Opt(Department),
          IDL.Opt(Timestamp),
          IDL.Opt(Timestamp),
        ],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'listTransactionsByDepartment' : IDL.Func(
        [Department],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [IDL.Nat], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'recordTransaction' : IDL.Func([TransactionInput], [Transaction], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
    'sendNotification' : IDL.Func([NotificationInput], [Notification], []),
    'submitReview' : IDL.Func([ReviewInput], [Review], []),
    'updateEmployeeProfile' : IDL.Func(
        [IDL.Nat, EmployeeProfileInput],
        [IDL.Opt(EmployeeProfile)],
        [],
      ),
    'updateLocation' : IDL.Func(
        [IDL.Nat, LocationInput],
        [IDL.Opt(Location)],
        [],
      ),
    'updateMeeting' : IDL.Func([IDL.Nat, MeetingInput], [IDL.Opt(Meeting)], []),
    'updatePerformanceScore' : IDL.Func([IDL.Nat, IDL.Float64], [IDL.Bool], []),
    'updateUser' : IDL.Func(
        [IDL.Principal, UserProfileInput],
        [IDL.Opt(UserProfile)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };