/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'id' : bigint,
  'checkIn' : bigint,
  'userId' : Principal,
  'checkOut' : [] | [bigint],
  'gpsLat' : number,
  'gpsLng' : number,
}
export type Department = { 'BAR' : null } |
  { 'BARBERSHOP' : null } |
  { 'GAS_STATION' : null };
export interface EmployeeProfile {
  'id' : bigint,
  'salary' : number,
  'performanceScore' : number,
  'userId' : Principal,
  'department' : Department,
  'position' : string,
}
export interface EmployeeProfileInput {
  'salary' : number,
  'userId' : Principal,
  'department' : Department,
  'position' : string,
}
export type ExternalBlob = Uint8Array;
export interface Location {
  'id' : bigint,
  'name' : string,
  'radius' : number,
  'gpsLat' : number,
  'gpsLng' : number,
}
export interface LocationInput {
  'name' : string,
  'radius' : number,
  'gpsLat' : number,
  'gpsLng' : number,
}
export interface Meeting {
  'id' : bigint,
  'title' : string,
  'participants' : Array<Principal>,
  'date' : bigint,
  'createdBy' : Principal,
  'description' : string,
}
export interface MeetingInput {
  'title' : string,
  'participants' : Array<Principal>,
  'date' : bigint,
  'description' : string,
}
export interface Notification {
  'id' : bigint,
  'title' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'isRead' : boolean,
  'message' : string,
}
export interface NotificationInput {
  'title' : string,
  'userId' : Principal,
  'message' : string,
}
export interface Report {
  'to' : Timestamp,
  'expense' : number,
  'period' : ReportPeriod,
  'from' : Timestamp,
  'income' : number,
  'profit' : number,
  'department' : [] | [Department],
}
export type ReportPeriod = { 'MONTHLY' : null } |
  { 'DAILY' : null } |
  { 'YEARLY' : null } |
  { 'WEEKLY' : null };
export interface Review {
  'id' : bigint,
  'date' : bigint,
  'reviewedBy' : Principal,
  'score' : number,
  'employeeId' : bigint,
  'comments' : string,
}
export interface ReviewInput {
  'score' : number,
  'employeeId' : bigint,
  'comments' : string,
}
export type Role = { 'ADMIN' : null } |
  { 'OWNER' : null } |
  { 'EMPLOYEE' : null };
export type Timestamp = bigint;
export interface Transaction {
  'id' : bigint,
  'transactionType' : TransactionType,
  'date' : Timestamp,
  'createdBy' : Principal,
  'notes' : string,
  'category' : string,
  'department' : Department,
  'amount' : number,
}
export interface TransactionInput {
  'transactionType' : TransactionType,
  'notes' : string,
  'category' : string,
  'department' : Department,
  'amount' : number,
}
export type TransactionType = { 'INCOME' : null } |
  { 'EXPENSE' : null };
export interface UserProfile {
  'id' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'photoUrl' : ExternalBlob,
  'isActive' : boolean,
  'email' : string,
}
export interface UserProfileInput {
  'name' : string,
  'role' : Role,
  'photoUrl' : ExternalBlob,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[Principal, Role], boolean>,
  'checkIn' : ActorMethod<[number, number], AttendanceRecord>,
  'checkOut' : ActorMethod<[], [] | [AttendanceRecord]>,
  'createEmployeeProfile' : ActorMethod<
    [EmployeeProfileInput],
    EmployeeProfile
  >,
  'createLocation' : ActorMethod<[LocationInput], Location>,
  'createMeeting' : ActorMethod<[MeetingInput], Meeting>,
  'createUser' : ActorMethod<[Principal, UserProfileInput], UserProfile>,
  'deactivateUser' : ActorMethod<[Principal], boolean>,
  'deleteEmployeeProfile' : ActorMethod<[bigint], boolean>,
  'deleteLocation' : ActorMethod<[bigint], boolean>,
  'deleteMeeting' : ActorMethod<[bigint], boolean>,
  'deleteNotification' : ActorMethod<[bigint], boolean>,
  'deleteTransaction' : ActorMethod<[bigint], boolean>,
  'generateReport' : ActorMethod<
    [ReportPeriod, [] | [Department], Timestamp, Timestamp],
    Report
  >,
  'getAttendanceRecord' : ActorMethod<[bigint], [] | [AttendanceRecord]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployeeProfile' : ActorMethod<[bigint], [] | [EmployeeProfile]>,
  'getLocation' : ActorMethod<[bigint], [] | [Location]>,
  'getMeeting' : ActorMethod<[bigint], [] | [Meeting]>,
  'getTransaction' : ActorMethod<[bigint], [] | [Transaction]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'listAttendanceByUser' : ActorMethod<[Principal], Array<AttendanceRecord>>,
  'listEmployees' : ActorMethod<[], Array<EmployeeProfile>>,
  'listEmployeesByDepartment' : ActorMethod<
    [Department],
    Array<EmployeeProfile>
  >,
  'listLocations' : ActorMethod<[], Array<Location>>,
  'listMeetings' : ActorMethod<[], Array<Meeting>>,
  'listMyAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'listMyNotifications' : ActorMethod<[], Array<Notification>>,
  'listReviewsForEmployee' : ActorMethod<[bigint], Array<Review>>,
  'listTransactions' : ActorMethod<
    [
      [] | [TransactionType],
      [] | [Department],
      [] | [Timestamp],
      [] | [Timestamp],
    ],
    Array<Transaction>
  >,
  'listTransactionsByDepartment' : ActorMethod<
    [Department],
    Array<Transaction>
  >,
  'listUsers' : ActorMethod<[], Array<UserProfile>>,
  'markAllNotificationsRead' : ActorMethod<[], bigint>,
  'markNotificationRead' : ActorMethod<[bigint], boolean>,
  'recordTransaction' : ActorMethod<[TransactionInput], Transaction>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileInput], undefined>,
  'sendNotification' : ActorMethod<[NotificationInput], Notification>,
  'submitReview' : ActorMethod<[ReviewInput], Review>,
  'updateEmployeeProfile' : ActorMethod<
    [bigint, EmployeeProfileInput],
    [] | [EmployeeProfile]
  >,
  'updateLocation' : ActorMethod<[bigint, LocationInput], [] | [Location]>,
  'updateMeeting' : ActorMethod<[bigint, MeetingInput], [] | [Meeting]>,
  'updatePerformanceScore' : ActorMethod<[bigint, number], boolean>,
  'updateUser' : ActorMethod<[Principal, UserProfileInput], [] | [UserProfile]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];