/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfileInput {
    name: string;
    role: Role;
    photoUrl: ExternalBlob;
    email: string;
}
export interface UserProfile {
    id: Principal;
    name: string;
    createdAt: Timestamp;
    role: Role;
    photoUrl: ExternalBlob;
    isActive: boolean;
    email: string;
}
export type Timestamp = bigint;
export interface Location {
    id: bigint;
    name: string;
    radius: number;
    gpsLat: number;
    gpsLng: number;
}
export interface Meeting {
    id: bigint;
    title: string;
    participants: Array<Principal>;
    date: bigint;
    createdBy: Principal;
    description: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MeetingInput {
    title: string;
    participants: Array<Principal>;
    date: bigint;
    description: string;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface LocationInput {
    name: string;
    radius: number;
    gpsLat: number;
    gpsLng: number;
}
export interface Report {
    to: Timestamp;
    expense: number;
    period: ReportPeriod;
    from: Timestamp;
    income: number;
    profit: number;
    department?: Department;
}
export interface Transaction {
    id: bigint;
    transactionType: TransactionType;
    date: Timestamp;
    createdBy: Principal;
    notes: string;
    category: string;
    department: Department;
    amount: number;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface EmployeeProfileInput {
    salary: number;
    userId: Principal;
    department: Department;
    position: string;
}
export interface Notification {
    id: bigint;
    title: string;
    userId: Principal;
    createdAt: bigint;
    isRead: boolean;
    message: string;
}
export interface NotificationInput {
    title: string;
    userId: Principal;
    message: string;
}
export interface EmployeeProfile {
    id: bigint;
    salary: number;
    performanceScore: number;
    userId: Principal;
    department: Department;
    position: string;
}
export interface AttendanceRecord {
    id: bigint;
    checkIn: bigint;
    userId: Principal;
    checkOut?: bigint;
    gpsLat: number;
    gpsLng: number;
}
export interface ReviewInput {
    score: number;
    employeeId: bigint;
    comments: string;
}
export interface TransactionInput {
    transactionType: TransactionType;
    notes: string;
    category: string;
    department: Department;
    amount: number;
}
export interface Review {
    id: bigint;
    date: bigint;
    reviewedBy: Principal;
    score: number;
    employeeId: bigint;
    comments: string;
}
export enum Department {
    BAR = "BAR",
    BARBERSHOP = "BARBERSHOP",
    GAS_STATION = "GAS_STATION"
}
export enum ReportPeriod {
    MONTHLY = "MONTHLY",
    DAILY = "DAILY",
    YEARLY = "YEARLY",
    WEEKLY = "WEEKLY"
}
export enum Role {
    ADMIN = "ADMIN",
    OWNER = "OWNER",
    EMPLOYEE = "EMPLOYEE"
}
export enum TransactionType {
    INCOME = "INCOME",
    EXPENSE = "EXPENSE"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignUserRole(id: Principal, role: Role): Promise<boolean>;
    checkIn(gpsLat: number, gpsLng: number): Promise<AttendanceRecord>;
    checkOut(): Promise<AttendanceRecord | null>;
    createEmployeeProfile(input: EmployeeProfileInput): Promise<EmployeeProfile>;
    createLocation(input: LocationInput): Promise<Location>;
    createMeeting(input: MeetingInput): Promise<Meeting>;
    createUser(id: Principal, input: UserProfileInput): Promise<UserProfile>;
    deactivateUser(id: Principal): Promise<boolean>;
    deleteEmployeeProfile(id: bigint): Promise<boolean>;
    deleteLocation(id: bigint): Promise<boolean>;
    deleteMeeting(id: bigint): Promise<boolean>;
    deleteNotification(id: bigint): Promise<boolean>;
    deleteTransaction(id: bigint): Promise<boolean>;
    generateReport(period: ReportPeriod, department: Department | null, from: Timestamp, to: Timestamp): Promise<Report>;
    getAttendanceRecord(id: bigint): Promise<AttendanceRecord | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEmployeeProfile(id: bigint): Promise<EmployeeProfile | null>;
    getLocation(id: bigint): Promise<Location | null>;
    getMeeting(id: bigint): Promise<Meeting | null>;
    getTransaction(id: bigint): Promise<Transaction | null>;
    getUserProfile(userId: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllAttendance(): Promise<Array<AttendanceRecord>>;
    listAttendanceByUser(userId: Principal): Promise<Array<AttendanceRecord>>;
    listEmployees(): Promise<Array<EmployeeProfile>>;
    listEmployeesByDepartment(department: Department): Promise<Array<EmployeeProfile>>;
    listLocations(): Promise<Array<Location>>;
    listMeetings(): Promise<Array<Meeting>>;
    listMyAttendance(): Promise<Array<AttendanceRecord>>;
    listMyNotifications(): Promise<Array<Notification>>;
    listReviewsForEmployee(employeeId: bigint): Promise<Array<Review>>;
    listTransactions(txType: TransactionType | null, department: Department | null, fromTs: Timestamp | null, toTs: Timestamp | null): Promise<Array<Transaction>>;
    listTransactionsByDepartment(department: Department): Promise<Array<Transaction>>;
    listUsers(): Promise<Array<UserProfile>>;
    markAllNotificationsRead(): Promise<bigint>;
    markNotificationRead(id: bigint): Promise<boolean>;
    recordTransaction(input: TransactionInput): Promise<Transaction>;
    saveCallerUserProfile(input: UserProfileInput): Promise<void>;
    sendNotification(input: NotificationInput): Promise<Notification>;
    submitReview(input: ReviewInput): Promise<Review>;
    updateEmployeeProfile(id: bigint, input: EmployeeProfileInput): Promise<EmployeeProfile | null>;
    updateLocation(id: bigint, input: LocationInput): Promise<Location | null>;
    updateMeeting(id: bigint, input: MeetingInput): Promise<Meeting | null>;
    updatePerformanceScore(id: bigint, score: number): Promise<boolean>;
    updateUser(id: Principal, input: UserProfileInput): Promise<UserProfile | null>;
}
import type { AttendanceRecord as _AttendanceRecord, Department as _Department, EmployeeProfile as _EmployeeProfile, EmployeeProfileInput as _EmployeeProfileInput, ExternalBlob as _ExternalBlob, Location as _Location, Meeting as _Meeting, Report as _Report, ReportPeriod as _ReportPeriod, Role as _Role, Timestamp as _Timestamp, Transaction as _Transaction, TransactionInput as _TransactionInput, TransactionType as _TransactionType, UserProfile as _UserProfile, UserProfileInput as _UserProfileInput, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignUserRole(arg0: Principal, arg1: Role): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRole(arg0, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRole(arg0, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkIn(arg0: number, arg1: number): Promise<AttendanceRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIn(arg0, arg1);
                return from_candid_AttendanceRecord_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIn(arg0, arg1);
            return from_candid_AttendanceRecord_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkOut(): Promise<AttendanceRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkOut();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkOut();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createEmployeeProfile(arg0: EmployeeProfileInput): Promise<EmployeeProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployeeProfile(to_candid_EmployeeProfileInput_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_EmployeeProfile_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployeeProfile(to_candid_EmployeeProfileInput_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_EmployeeProfile_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLocation(arg0: LocationInput): Promise<Location> {
        if (this.processError) {
            try {
                const result = await this.actor.createLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLocation(arg0);
            return result;
        }
    }
    async createMeeting(arg0: MeetingInput): Promise<Meeting> {
        if (this.processError) {
            try {
                const result = await this.actor.createMeeting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMeeting(arg0);
            return result;
        }
    }
    async createUser(arg0: Principal, arg1: UserProfileInput): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, await to_candid_UserProfileInput_n24(this._uploadFile, this._downloadFile, arg1));
                return from_candid_UserProfile_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, await to_candid_UserProfileInput_n24(this._uploadFile, this._downloadFile, arg1));
            return from_candid_UserProfile_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivateUser(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0);
            return result;
        }
    }
    async deleteEmployeeProfile(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployeeProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployeeProfile(arg0);
            return result;
        }
    }
    async deleteLocation(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLocation(arg0);
            return result;
        }
    }
    async deleteMeeting(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMeeting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMeeting(arg0);
            return result;
        }
    }
    async deleteNotification(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotification(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async generateReport(arg0: ReportPeriod, arg1: Department | null, arg2: Timestamp, arg3: Timestamp): Promise<Report> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReport(to_candid_ReportPeriod_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_Report_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReport(to_candid_ReportPeriod_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_Report_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceRecord(arg0: bigint): Promise<AttendanceRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceRecord(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceRecord(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeProfile(arg0: bigint): Promise<EmployeeProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeProfile(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeProfile(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocation(arg0: bigint): Promise<Location | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocation(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocation(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMeeting(arg0: bigint): Promise<Meeting | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeeting(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeeting(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransaction(arg0: bigint): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllAttendance(): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllAttendance();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllAttendance();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAttendanceByUser(arg0: Principal): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAttendanceByUser(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAttendanceByUser(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEmployees(): Promise<Array<EmployeeProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEmployees();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEmployees();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEmployeesByDepartment(arg0: Department): Promise<Array<EmployeeProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEmployeesByDepartment(to_candid_Department_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEmployeesByDepartment(to_candid_Department_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLocations(): Promise<Array<Location>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLocations();
            return result;
        }
    }
    async listMeetings(): Promise<Array<Meeting>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMeetings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMeetings();
            return result;
        }
    }
    async listMyAttendance(): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyAttendance();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyAttendance();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyNotifications();
            return result;
        }
    }
    async listReviewsForEmployee(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReviewsForEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReviewsForEmployee(arg0);
            return result;
        }
    }
    async listTransactions(arg0: TransactionType | null, arg1: Department | null, arg2: Timestamp | null, arg3: Timestamp | null): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTransactions(to_candid_opt_n53(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n56(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n56(this._uploadFile, this._downloadFile, arg3));
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTransactions(to_candid_opt_n53(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n56(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n56(this._uploadFile, this._downloadFile, arg3));
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTransactionsByDepartment(arg0: Department): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTransactionsByDepartment(to_candid_Department_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTransactionsByDepartment(to_candid_Department_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsRead(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationRead(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async recordTransaction(arg0: TransactionInput): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.recordTransaction(to_candid_TransactionInput_n59(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Transaction_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordTransaction(to_candid_TransactionInput_n59(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Transaction_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfileInput_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfileInput_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendNotification(arg0: NotificationInput): Promise<Notification> {
        if (this.processError) {
            try {
                const result = await this.actor.sendNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendNotification(arg0);
            return result;
        }
    }
    async submitReview(arg0: ReviewInput): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0);
            return result;
        }
    }
    async updateEmployeeProfile(arg0: bigint, arg1: EmployeeProfileInput): Promise<EmployeeProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployeeProfile(arg0, to_candid_EmployeeProfileInput_n16(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployeeProfile(arg0, to_candid_EmployeeProfileInput_n16(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLocation(arg0: bigint, arg1: LocationInput): Promise<Location | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocation(arg0, arg1);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocation(arg0, arg1);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMeeting(arg0: bigint, arg1: MeetingInput): Promise<Meeting | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMeeting(arg0, arg1);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMeeting(arg0, arg1);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePerformanceScore(arg0: bigint, arg1: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePerformanceScore(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePerformanceScore(arg0, arg1);
            return result;
        }
    }
    async updateUser(arg0: Principal, arg1: UserProfileInput): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, await to_candid_UserProfileInput_n24(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, await to_candid_UserProfileInput_n24(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AttendanceRecord_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Department_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Department): Department {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_EmployeeProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeProfile): EmployeeProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ReportPeriod_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportPeriod): ReportPeriod {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Report_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AttendanceRecord]): AttendanceRecord | null {
    return value.length === 0 ? null : from_candid_AttendanceRecord_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Department]): Department | null {
    return value.length === 0 ? null : from_candid_Department_n22(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmployeeProfile]): EmployeeProfile | null {
    return value.length === 0 ? null : from_candid_EmployeeProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Meeting]): Meeting | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : from_candid_Transaction_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    checkIn: bigint;
    userId: Principal;
    checkOut: [] | [bigint];
    gpsLat: number;
    gpsLng: number;
}): {
    id: bigint;
    checkIn: bigint;
    userId: Principal;
    checkOut?: bigint;
    gpsLat: number;
    gpsLng: number;
} {
    return {
        id: value.id,
        checkIn: value.checkIn,
        userId: value.userId,
        checkOut: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.checkOut)),
        gpsLat: value.gpsLat,
        gpsLng: value.gpsLng
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    salary: number;
    performanceScore: number;
    userId: Principal;
    department: _Department;
    position: string;
}): {
    id: bigint;
    salary: number;
    performanceScore: number;
    userId: Principal;
    department: Department;
    position: string;
} {
    return {
        id: value.id,
        salary: value.salary,
        performanceScore: value.performanceScore,
        userId: value.userId,
        department: from_candid_Department_n22(_uploadFile, _downloadFile, value.department),
        position: value.position
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    createdAt: _Timestamp;
    role: _Role;
    photoUrl: _ExternalBlob;
    isActive: boolean;
    email: string;
}): Promise<{
    id: Principal;
    name: string;
    createdAt: Timestamp;
    role: Role;
    photoUrl: ExternalBlob;
    isActive: boolean;
    email: string;
}> {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n29(_uploadFile, _downloadFile, value.role),
        photoUrl: await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value.photoUrl),
        isActive: value.isActive,
        email: value.email
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: _Timestamp;
    expense: number;
    period: _ReportPeriod;
    from: _Timestamp;
    income: number;
    profit: number;
    department: [] | [_Department];
}): {
    to: Timestamp;
    expense: number;
    period: ReportPeriod;
    from: Timestamp;
    income: number;
    profit: number;
    department?: Department;
} {
    return {
        to: value.to,
        expense: value.expense,
        period: from_candid_ReportPeriod_n37(_uploadFile, _downloadFile, value.period),
        from: value.from,
        income: value.income,
        profit: value.profit,
        department: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.department))
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transactionType: _TransactionType;
    date: _Timestamp;
    createdBy: Principal;
    notes: string;
    category: string;
    department: _Department;
    amount: number;
}): {
    id: bigint;
    transactionType: TransactionType;
    date: Timestamp;
    createdBy: Principal;
    notes: string;
    category: string;
    department: Department;
    amount: number;
} {
    return {
        id: value.id,
        transactionType: from_candid_TransactionType_n49(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        createdBy: value.createdBy,
        notes: value.notes,
        category: value.category,
        department: from_candid_Department_n22(_uploadFile, _downloadFile, value.department),
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    BAR: null;
} | {
    BARBERSHOP: null;
} | {
    GAS_STATION: null;
}): Department {
    return "BAR" in value ? Department.BAR : "BARBERSHOP" in value ? Department.BARBERSHOP : "GAS_STATION" in value ? Department.GAS_STATION : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ADMIN: null;
} | {
    OWNER: null;
} | {
    EMPLOYEE: null;
}): Role {
    return "ADMIN" in value ? Role.ADMIN : "OWNER" in value ? Role.OWNER : "EMPLOYEE" in value ? Role.EMPLOYEE : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    MONTHLY: null;
} | {
    DAILY: null;
} | {
    YEARLY: null;
} | {
    WEEKLY: null;
}): ReportPeriod {
    return "MONTHLY" in value ? ReportPeriod.MONTHLY : "DAILY" in value ? ReportPeriod.DAILY : "YEARLY" in value ? ReportPeriod.YEARLY : "WEEKLY" in value ? ReportPeriod.WEEKLY : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    INCOME: null;
} | {
    EXPENSE: null;
}): TransactionType {
    return "INCOME" in value ? TransactionType.INCOME : "EXPENSE" in value ? TransactionType.EXPENSE : value;
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmployeeProfile>): Array<EmployeeProfile> {
    return value.map((x)=>from_candid_EmployeeProfile_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n47(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n27(_uploadFile, _downloadFile, x)));
}
function to_candid_Department_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department): _Department {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_EmployeeProfileInput_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeProfileInput): _EmployeeProfileInput {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ReportPeriod_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportPeriod): _ReportPeriod {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionInput_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionInput): _TransactionInput {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfileInput_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfileInput): Promise<_UserProfileInput> {
    return await to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department | null): [] | [_Department] {
    return value === null ? candid_none() : candid_some(to_candid_Department_n18(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType | null): [] | [_TransactionType] {
    return value === null ? candid_none() : candid_some(to_candid_TransactionType_n54(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    salary: number;
    userId: Principal;
    department: Department;
    position: string;
}): {
    salary: number;
    userId: Principal;
    department: _Department;
    position: string;
} {
    return {
        salary: value.salary,
        userId: value.userId,
        department: to_candid_Department_n18(_uploadFile, _downloadFile, value.department),
        position: value.position
    };
}
async function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: Role;
    photoUrl: ExternalBlob;
    email: string;
}): Promise<{
    name: string;
    role: _Role;
    photoUrl: _ExternalBlob;
    email: string;
}> {
    return {
        name: value.name,
        role: to_candid_Role_n10(_uploadFile, _downloadFile, value.role),
        photoUrl: await to_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value.photoUrl),
        email: value.email
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionType: TransactionType;
    notes: string;
    category: string;
    department: Department;
    amount: number;
}): {
    transactionType: _TransactionType;
    notes: string;
    category: string;
    department: _Department;
    amount: number;
} {
    return {
        transactionType: to_candid_TransactionType_n54(_uploadFile, _downloadFile, value.transactionType),
        notes: value.notes,
        category: value.category,
        department: to_candid_Department_n18(_uploadFile, _downloadFile, value.department),
        amount: value.amount
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    ADMIN: null;
} | {
    OWNER: null;
} | {
    EMPLOYEE: null;
} {
    return value == Role.ADMIN ? {
        ADMIN: null
    } : value == Role.OWNER ? {
        OWNER: null
    } : value == Role.EMPLOYEE ? {
        EMPLOYEE: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department): {
    BAR: null;
} | {
    BARBERSHOP: null;
} | {
    GAS_STATION: null;
} {
    return value == Department.BAR ? {
        BAR: null
    } : value == Department.BARBERSHOP ? {
        BARBERSHOP: null
    } : value == Department.GAS_STATION ? {
        GAS_STATION: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportPeriod): {
    MONTHLY: null;
} | {
    DAILY: null;
} | {
    YEARLY: null;
} | {
    WEEKLY: null;
} {
    return value == ReportPeriod.MONTHLY ? {
        MONTHLY: null
    } : value == ReportPeriod.DAILY ? {
        DAILY: null
    } : value == ReportPeriod.YEARLY ? {
        YEARLY: null
    } : value == ReportPeriod.WEEKLY ? {
        WEEKLY: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    INCOME: null;
} | {
    EXPENSE: null;
} {
    return value == TransactionType.INCOME ? {
        INCOME: null
    } : value == TransactionType.EXPENSE ? {
        EXPENSE: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
